version: '3.9'
services:
  email-verify:
    container_name: "email-verify"
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5757:3000"
    restart: always
    env_file:
      - .env
